### PR TITLE
Add favicons

### LINKED ISSUE #272: Add DistrictBuilder favicon
We should add a favicon to the site using the new DB logo.

### PR DESCRIPTION
**Pull request by jfrankl**
## Overview

Just adding some favicons over here.

### Demo

Screen Shot 2020-09-01 at 11 02 23 PM
Screen Shot 2020-09-01 at 11 02 30 PM

## Testing Instructions

- Open the application
- Do you see favicons in places you'd expect to see favicons?

Closes #272

### CODE REVIEW

**Review by alexelash — APPROVED** [review]
Screen Shot 2020-09-02 at 1 30 16 PM
Favicon-tastic

**Comment by jfrankl** [comment]
@alexelash thanks for the review

**Comment by pcaisse** [comment]
I was just referring to this PR for another CRA project that needs its favicons updated and I could be wrong but I think the `favicon-32x32.png` and `favicon-16x16.png` images aren't used. I'm not super familiar with `manifest.json` but it seems like the `icons` property should look like this:
```
  "icons": [
    {
      "src": "favicon-32x32.png",
      "sizes": "32x32",
      "type": "image/png"
    },
    {
      "src": "favicon-16x16.png",
      "sizes": "16x16",
      "type": "image/png"
    },
    {
      "src": "favicon.ico",
      "sizes": "48x48",
      "type": "image/x-icon"
    }
  ],
```

Does that seem right to you @jfrankl ?

**Comment by jfrankl** [comment]
@pcaisse I typically use a [favicon generator](https://realfavicongenerator.net/) and upload whatever that gives me. I'd recommend using something like that.

**Pull request merged**
