### PR TITLE
Style Evaluate Mode panel

### PR DESCRIPTION
**Pull request by alexelash**
## Overview
Design pass of the Evaluate mode panel, button, and the legend over top of the map.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo
Screen Shot 2021-04-30 at 10 16 18 PM
Screen Shot 2021-04-30 at 10 19 39 PM
Screen Shot 2021-04-30 at 10 23 01 PM

### Notes
- I had to set a pixel width for the Evaluate sidebar so it would be the same width as the Districts sidebar... which didn't feel quite right but I couldn't figure out another solution. Open to feedback on this.
- Same ^ for the height of the Evaluate button in order to add the bottom border.
- I added a table heading for the Splits table - "County" and "Split". Not sure if this is right.

## Testing Instructions
- `git pull`
- Click the Evaluate button in top right of the screen of a project.
- Click each box in the summary panel and scroll within the side panel to see how the table performs.
- Note the legend on the map for each box in the summary panel.

~Closes #XXX~

### CODE REVIEW

**Review by maurizi — CHANGES_REQUESTED** [review]
I'll leave a full review to @jfrankl but I noticed a few small cleanups.

**Comment by alexelash** [comment]
Thanks @maurizi! Just committed those.

**Comment by jfrankl** [comment]
Taking a look at this now.

**Review by jfrankl — CHANGES_REQUESTED** [review]
This looks so good! Thanks @alexelash. I had three pieces of visual feedback. The one about a missing number is just in case you accidentally deleted that in your style cleanup, but it might be an issue for a developer.

Screen Shot 2021-05-12 at 3 45 57 PM
Screen Shot 2021-05-12 at 3 46 08 PM

**Comment by alexelash** [comment]
@jfrankl 

Thanks for the feedback. That's all updated in the most recent commit, and ready for another look. Here's Equal Pop:
Screen Shot 2021-05-13 at 10 34 12 AM
Screen Shot 2021-05-13 at 10 35 18 AM

I think the Deviation (%) column should be left-aligned, in order to align the swatches.

Only thing I didn't touch is the note about the first number not appearing in the Equal Pop panel. I do think it is a note for developers because I see the variable in the code - it's just not displaying a number:
Screen Shot 2021-05-13 at 10 41 52 AM

**Review by jfrankl — APPROVED** [review]
Looks good!

**Review by maurizi — APPROVED** [review]

**Pull request merged**
