### PR TITLE
Make paintbrush selection tool configurable by slider 

### LINKED ISSUE #742: Add size control to paintbrush tool
We want to add a size control to the paintbrush to make filling in larger areas easier.

[Wireframe here](https://share.goabstract.com/d1beff32-45f8-4987-af0f-840d97507d0b?mode=design&sha=09b392079f20d92a20fe38878b27420f0bd1e703)

**Note:** the wireframe differs from the AC. Implement what is described in the AC, but use the wireframe as a visual guide.

AC:
* When the user clicks on the paintbrush tool, an input range (slider) appears
* The slider is visible while the paintbrush tool is selected. It disappears when another tool is selected.
* Options should be 1, 2, 3, 4, 5 (there are five sizes/stops on the slider -- *this is different than the wireframe*)
* Option 1 should be the same size brush as is currently implemented
* 1 should be the default
* Each step should increase the brush size by a certain radius, up to some max

**Note:** It's not clear what the max size or size step should be. Feel free to experiment with sizing to see how it feels when implementing.

### PR DESCRIPTION
**Pull request by kevinearldenny**
## Overview

From #825 :

- There is a slider that's styled
- The slider will be toggled appropriately based on selection tool
- The slider remembers the size you picked last
- A slider circle is shown on the page that corresponds to the size you picked (NOTE: This is not specified as required in the issue, but I think we need to somehow visually indicate the paintbrush area as you're using it)

Newly added:

- Paintbrush selection tool selects all elements within brush area for all radii

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Notes

There are some scenarios where certain geounits are not selected at certain zoom levels, likely due to tile layer issues. Thus far, I have only observed this happening with Dauphin County, PA at high zoom levels. It feels a bit wonky, but since you can select the areas fine by zooming in a bit it doesn't seem to be a _huge_ problem - but potentially it is something worth looking into a little further

image

## Testing Instructions

- Select the paintbrush tool and the slider should show
- Default should be 1
- Select a different size
- Choose a different selection tool and the slider should be hidden
- Choose the paintbrush tool again and it should have remembered your size from before
- Click and hold and drag to select features on the map and you should see a partially opaque circle which corresponds to the size you choose
- All features under the paintbrush tool are selected as you drag, not just what's directly intersecting with your cursor

Closes #742

### CODE REVIEW

**Comment by maurizi** [comment]
@kevinearldenny can you rebase this on the latest `develop`?

**Comment by kevinearldenny** [comment]
> @kevinearldenny can you rebase this on the latest `develop`?

Okay, this is now rebased and ready for review

**Review by maurizi — CHANGES_REQUESTED** [review]
There is 1 piece of the AC from the original issue that isn't accounted for:

> - Option 1 should be the same size brush as is currently implemented
> - 1 should be the default

We want to retain the current "pencil"-size brush as an option, and as the default for the paintbrush tool.

**Review by maurizi — APPROVED** [review]
👍

**Pull request merged**
