### PR TITLE
Upgrade development database to PostgreSQL 12.2 and PostGIS 3

### LINKED ISSUE #339: Upgrade to PostgreSQL 12 in development environment
Upgrade the container image used by the local development environment to use PostgreSQL 12.x. Ensure that the version we settle on is available via Amazon RDS.

See: https://quay.io/repository/azavea/postgis?tag=latest&tab=tags

### LINKED ISSUE #340: Upgrade PostgreSQL in staging environment
Upgrade the version of PostgreSQL used in staging to align with https://github.com/PublicMapping/districtbuilder/issues/339. Ensure that any steps taken are documented so that they can be used as input to a plan for the PostgreSQL upgrade in production.

### PR DESCRIPTION
**Pull request by ColeKettler**
## Overview

Upgrades the `docker-compose.yml` `database` service definition to use PostgreSQL 12.2 and PostGIS 3.

RDS supports PostgreSQL 12.2 and 12.3, so we'll be able to have version parity between development and staging / production.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### To migrate an existing development database
- Run the following commands to backup the PostgreSQL 11 database and restore it to PostgreSQL 12:
  ```#bash
  # Use the Compose service definition for PostgreSQL 11
  git checkout develop
  # Create a logical backup 
  docker-compose exec -T database bash -c 'pg_dumpall -U $POSTGRES_USER' > dump.sql
  # Checkout this PR to use the Compose service definition for PostgreSQL 12
  git checkout feature/cek/postgresql-12-development
  # Recreate the database service with a new data volume
  docker-compose up -dV database
  # Import the logical backup
  docker-compose exec -T database bash -c 'psql -U $POSTGRES_USER' < dump.sql
  ```
- Run `./scripts/update` to build all of the application containers.
- Run `./scripts/migration` and confirm that no migrations need to be run.
- Run `./scripts/server` and verify that you are able to log in with your existing username and password.

### For a new development database
- Run `docker-compose up -dV` to disassociate the development database from its old data volume and recreate it with a new volume.
- Run `./scripts/update` to build all of the application containers.
- Run `./scripts/migration` to migrate the new database.
- Run `./scripts/server` and verify that you are able to register a new user and log in.

Closes #339

### CODE REVIEW

**Comment by ColeKettler** [comment]
For ease of reference, here's how to migrate a development database without needing to recreate it once this PR is merged:

```#bash
# Checkout a commit prior to this PR to use the Compose service definition for PostgreSQL 11
git checkout 87363e2
# Create a logical backup
docker-compose exec -T database bash -c 'pg_dumpall -U $POSTGRES_USER' > dump.sql
# Pull down `develop` to use the Compose service definition for PostgreSQL 12
git checkout develop && git pull
# Recreate the database service with a new data volume
docker-compose up -dV database
# Import the logical backup
docker-compose exec -T database bash -c 'psql -U $POSTGRES_USER' < dump.sql
```

**Review by rbreslow — COMMENTED** [review]
I was able to test spinning up a new development environment from scratch, but I run into this when I follow your instructions to migrate an existing development environment.

```bash
[rocky@algiers districtbuilder] (develop)$ ./scripts/update
. . .
[rocky@algiers districtbuilder] (develop)$ docker-compose exec -T database bash -c 'pg_dumpall -U $POSTGRES_USER' > dump.sql
[rocky@algiers districtbuilder] (develop %)$ git checkout feature/cek/postgresql-12-development
Switched to branch 'feature/cek/postgresql-12-development'
Your branch is up to date with 'origin/feature/cek/postgresql-12-development'.
[rocky@algiers districtbuilder] (feature/cek/postgresql-12-development %)$ docker-compose up -dV database
Recreating districtbuilder_database_1 ... done
[rocky@algiers districtbuilder] (feature/cek/postgresql-12-development %)$ docker-compose exec -T database bash -c 'psql -U $POSTGRES_USER' < dump.sql

psql: error: could not connect to server: FATAL:  database "districtbuilder" does not exist
```

**Comment by ColeKettler** [comment]
@rbreslow Whoah, that's surprising. What do you get if you get into `psql` and run `\l`? Does that database exist in the first place?

I've wiped my DB a few times while testing out the upgrade, recreated it with `./scripts/update`, and then manually created some data to go in it in case that's a potential discrepancy.

Also, I added in the migration instructions primarily as a convenience and to verify that previous data would be logically compatible with the newer version. I'll defer to you on how much additional time investment this part of the testing instructions is worth!

**Review by rbreslow — APPROVED** [review]
> I'll defer to you on how much additional time investment this part of the testing instructions is worth!

Yeah, I can't even get the development environment to come back up. I keep running into this issue and it looks like nothing is resolving it short of pruning my Docker system each time.

```bash
ERROR: for districtbuilder_database_1  You cannot remove a running container 07c242c5a483fef5ef417d1c816828881eb4a2cebaddd84bb608a19aa41eda85. Stop the container before attempting removal or force remove
```

I'm just going to approve this PR so it can move along, but keep in mind I wasn't able to follow the testing instructions for creating a workable database dump.

**Comment by ColeKettler** [comment]
@rbreslow Okay, that seems reasonable. I'm not certain what's causing this discrepancy between our systems, but I agree that it's not worth holding back on merging this. I think it will be cleanest for folks to recreate their development databases rather than potentially burn troubleshooting time if we run into the same issues.

**Pull request merged**
