### PR TITLE
parameterize rules so both staging and prod can exist

### PR DESCRIPTION
**Pull request by BryanQuigley**
## Overview

This should allow us to tell the difference between prod and staging for reindexing.

### Checklist

- [ ] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

## Testing Instructions

- this has to just be deployed everywhere?

Closes: #1129

### CODE REVIEW

**Comment by BryanQuigley** [comment]
This looks mostly correct to me. I don't like that both staging and prod are trying to rename the same rules, but I think it will go like:
1. Staging is deployed as above
2. Prod when deployed ends up creating all new infra. (as above it's renaming anything with staging in it to prod *or* it's changing the name to (known after apply). )

**Comment by ddohler** [comment]
> Prod when deployed ends up creating all new infra. (as above it's renaming anything with staging in it to prod or it's changing the name to (known after apply). )

I _think_ this sounds right. Right now both staging and production are referencing the same ARN in their Terraform state, so when we alter that resource, the plan updates based on the current state and both plans try to alter the same resource. But once staging is deployed, the ARN in the production state will no longer point to any existing resource (because the staging deploy will have changed it). Then I think a subsequent production deploy _should_ detect that and create the resource from scratch instead. But I'm operating from limited experience here, and I'm not sure how optimistic `terraform plan` is about whether the state of the world matches what it has stored in `state` -- it might be necessary to run something like `terraform apply --refresh-only` to update the production state before running the production deploy.

Alternatively, another route might be to do an intermediate deploy to remove the resource first, and then add it back in with the proper parameterization. That would still encounter the same issue with states potentially getting out of sync across the shared resource, but I'm assuming that Terraform is more likely to shrug and carry on if a thing it wants to delete doesn't exist than if a thing it wants to alter doesn't.

**Review by maurizi — APPROVED** [review]
> Prod when deployed ends up creating all new infra. (as above it's renaming anything with staging in it to prod or it's changing the name to (known after apply). )

As we discussed, a simple path forward on testing this is to merge it and let CI redeploy ~production~ staging, and then we can double-check if applying this to production will result in a new rule.

Before merging - don't forget to update the `CHANGELOG` with a reference to this PR

**Comment by BryanQuigley** [comment]
Confirmed on production that with the rename on staging new rules/targets will be created.
# aws_cloudwatch_event_rule.reindex_task will be created
 # aws_cloudwatch_event_target.reindex_task will be created

**Pull request merged**
