### PR TITLE
Add product tour

### LINKED ISSUE #433: Add a product tour for new users
For new users, as a way to welcome them to DistrictBuilder and quickly introduce them to the UI, we should present them with an optional product tour.

We've put a lot of work into making the UI clear, but DistrictBuilder is still a complex tool and there are some unconventional ideas if you are unfamiliar with redistricting. A tour would serve as a way to make users feel more comfortable and give them enough information to feel like they can explore without trying to cover everything. At the end of the brief tour, we can link to the docs for a more in depth read.

### Sections of the tour

1. What's going on in the sidebar and what is the general goal (contiguous districts with near-equal populations)
2. Toggling between different geounit levels
3. What to do when you're done: share, export, evaluate (when available)

### Implementation
I think this work could be completed primarily through the design team using a library like https://react-joyride.com/ or https://reactour.js.org/. We would need some developer support to note in the database whether we should show the tour to a user (once they finish the tour or skip it, they should never see it again)

### PR DESCRIPTION
**Pull request by alexelash**
## Overview
This PR adds a product tour for new users that explains redistricting and DistrictBuilder basics.

### Checklist

- [x] Description of PR is in an appropriate section of `CHANGELOG.md` and grouped with similar changes, if possible

### Demo
Screen Shot 2020-10-13 at 11 40 01 AM
Screen Shot 2020-10-13 at 11 40 24 AM
Screen Shot 2020-10-13 at 11 41 25 AM

### Notes
- For some reason, having the tour start not-centered is causing issues with the map. It looks like the map canvas is accounting for a scrollbar that isn't there:
    Screen Shot 2020-10-13 at 10 59 18 AM
    Unfortunately, even when the tour ends the spacing remains. It only goes away if you resize the browser, and I tried a bunch of different things to resolve it but the only thing that worked was centering the first step. As a result in this PR that's what I've done:
    Screen Shot 2020-10-13 at 11 11 26 AM
    Let me know if you'd still prefer to have it in the corner.
- Unless we use custom components, we don't seem to have a ton of styling options for the buttons. Most notably, the focus state is using the browser default. I got as close to our button / links styles as possible.
- There is by default an X in the top-right corner of Joyride Tours, but it didn't act the way I expected (clicking the X proceeds to the next step, but I expected it to skip the tour) so I hid it.

## Testing Instructions

**Notes for testing:** 
1. You will need 3 user accounts, each with at least 1 project, for testing.
2. There are server changes as whether a tour has been seen or not is attached to a user's account, so you will need this to be up-to-date.

**Instructions:**
- `git pull`
- Run yarn install to get the the joyride package
- Log into your 1st account.
- Enter any map project. You should see the tour.
- Click "Next" and go through each step of the tour. 
- On step 7, you'll be instructed to click on the map. Select some counties on the map -- this should be possible.
- On step 7, you'll be instructed to click "Accept". Select "Accept" -- this should be possible.
- When you are finished, refresh the page or enter another project. The tour should **not** appear.
- Log into your 2nd account.
- Enter a project. You should see the tour. Now click "No thanks" on the first step of the tour. 
- Refresh the page or enter another project. You should **not** see the tour.
- Log into your 3rd account.
- Enter a project. You should see the tour. Proceed through the tour, and at some point click "Skip tour".
- Refresh the page or enter another project. You should **not** see the tour.
- Copy/paste the map's url into an incognito browser window. You should **not** see the tour.

Closes #433

### CODE REVIEW

**Review by kshepard — CHANGES_REQUESTED** [review]
The sixth step is showing up below the fold for me (in Firefox on Linux): 

tour

**Review by kshepard — APPROVED** [review]
Looks good! I made one minor suggestion, and this should be good to merge once the small issue I pointed out with step six is addressed. :lizard:

**Comment by jfrankl** [comment]
> The sixth step is showing up below the fold for me (in Firefox on Linux):
> 
> tour

Happens for me too on Chrome on a Mac.

**Comment by jfrankl** [comment]
So good! Here are a few bits of feedback.

For readability and accessibility, consider left-aligning blocks of text.  In my opinion, the centered text works fine on that first step with Mandy, but I'd switch to left for the other steps.

For the step about selecting a county on the map: when I wrote that, I wasn't thinking about having it be an interactive step. But I like it how you have it set up! To reinforce the interaction, I think it might be helpful to add some extra copy to make it more clear that we're hoping the user will interact with map right now, as opposed to after the tour when they're building the map. I'm thinking something like "Try it now" with a slightly different formatting, such as: **Try it now:** click on a county ...
Screen Shot 2020-10-14 at 12 05 22 PM

For the step about the entire district sidebar, I think it might work better if the tour were anchored more towards the top of the sidebar instead of the vertical middle. On a map with fewer districts, it can look like the arrow is pointing at a blank space. I think this is minor, so if it's not an easy fix, I wouldn't worry about it.

Screen Shot 2020-10-14 at 12 01 25 PM

**Comment by jfrankl** [comment]
Hey @alexelash I think I got the first step of the tour working in the bottom right corner. The trick seems to be adding a new element to the page that has a not-small width. I ended up with a 300px width transparent rectangle, which seems to work consistently on Firefox and Chrome.

https://github.com/PublicMapping/districtbuilder/tree/feature/jdf/product-tour

**Comment by alexelash** [comment]
@kshepard & @jfrankl Step 6 should be fixed -- I checked in Firefox and Edge (I just needed to reduce the width of the step):
Screen Shot 2020-10-15 at 12 20 28 PM
Screen Shot 2020-10-15 at 12 24 30 PM

Jeff and I also worked together to figure out the spacing issue for the first step, so it now starts in the bottom right again. It required a combination of removing the code that initialized the tour after the map loads AND what Jeff suggested in a comment above:
Screen Shot 2020-10-15 at 12 20 46 PM

I moved step 4 to appear near the top of the sidebar:
Screen Shot 2020-10-15 at 12 32 43 PM

Jeff: the first three steps looked better centered to me (since the second 2 are centered on the screen), so I kept those centered and all else is left-aligned. 

This is ready for another look.

**Review by kshepard — APPROVED** [review]
Looking good. I wanted to call out that there's some hardcoded geolevel text in some places, while it's dynamic in other places. I don't know if it's a priority to make this fully dynamic now, but when we eventually add a region that doesn't have these three geolevels, we'll want to make sure to update it accordingly.

**Comment by jfrankl** [comment]
Two small things:

This screen refers to the population for D1 increases, but the tour covers it up so you can't see it. I think anchoring this on the bottom or maybe middle would fix the issue.
Screen Shot 2020-10-15 at 9 58 22 AM

In other circumstances I would like this "try it now" message. However, in this case, it's a little tricky in the app to make changes once you accept them. You'd either need to access the undo button or switch to the null district and re-select and accept. It's not impossible, but it's enough that I don't want to make as strong of a push to get users to press Accept at this stage. I want them to know about it, though. Suggested fix: just remove the try it now.
Screen Shot 2020-10-15 at 9 58 58 AM

**Comment by alexelash** [comment]
@kshepard Makes sense. Should I make an issue for that, or will that be internally tracked?

@jfrankl Thanks, I made those adjustments:
Screen Shot 2020-10-15 at 3 45 51 PM
Screen Shot 2020-10-15 at 3 46 01 PM

**Comment by kshepard** [comment]
It'd be great if you can add an issue for tracking that, thanks.

**Review by jfrankl — APPROVED** [review]
https://www.youtube.com/watch?v=B8tZtTVhpd8

**Comment by alexelash** [comment]
@kshepard cool just created #475 for that. Thanks!

**Pull request merged**
